# Generated by Django 5.1.2 on 2024-10-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AnnualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Ключевое мероприятие',
                'verbose_name_plural': 'Ключевые мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие страницы',
                'verbose_name_plural': 'Мероприятия страниц',
            },
        ),
        migrations.CreateModel(
            name='Eventss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/', verbose_name='Миниатюра видео')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок видео')),
                ('description', models.TextField(verbose_name='Описание видео')),
                ('video_url', models.URLField(verbose_name='URL видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
        migrations.CreateModel(
            name='VideoContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/', verbose_name='Миниатюра видео')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок видео')),
                ('description', models.TextField(verbose_name='Описание видео')),
                ('video_url', models.URLField(verbose_name='URL видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
    ]
