# Generated by Django 5.1.2 on 2024-10-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='названия')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страница Амбассадорство ',
                'verbose_name_plural': 'Страница Амбассадорство',
            },
        ),
        migrations.CreateModel(
            name='AmbassadorshipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Ключевое мероприятие',
                'verbose_name_plural': 'Ключевые мероприятия',
            },
        ),
    ]
