# Generated by Django 5.1.2 on 2024-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorshipimage',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описания'),
        ),
    ]
