# Generated by Django 5.1.2 on 2024-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contentblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('community', 'Преимущества для сообщества'), ('events', 'Преимущества для мероприятий'), ('suppliers', 'Поставщики'), ('partners', 'Партнеры')], max_length=50, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контентный блок',
                'verbose_name_plural': 'Контентные блоки',
            },
        ),
        migrations.CreateModel(
            name='Educert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие страницы',
                'verbose_name_plural': 'Мероприятия страниц',
            },
        ),
        migrations.CreateModel(
            name='Videoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео ',
            },
        ),
    ]
