# Generated by Django 5.1.2 on 2024-10-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=500, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='названия')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга  страницы',
                'verbose_name_plural': 'Услуга страниц',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
            ],
            options={
                'verbose_name': 'услуг',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('additional_text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Участие в проекте',
                'verbose_name_plural': 'Участия в проектах',
            },
        ),
    ]
