# Generated by Django 5.1.2 on 2024-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_the_community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RenameModel(
            old_name='PageContent',
            new_name='about',
        ),
    ]
