# Generated by Django 5.1.2 on 2024-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_the_community', '0002_communityimage_rename_pagecontent_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityimage',
            name='description',
            field=models.TextField(verbose_name='Описание видео'),
        ),
    ]
