# Generated by Django 5.1.2 on 2024-10-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_education_membership_service_сommunities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambassador',
            options={'verbose_name': 'Посол', 'verbose_name_plural': 'Послы'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name': 'Контентный блок', 'verbose_name_plural': 'Контентные блоки'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образования'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Изображение мероприятия', 'verbose_name_plural': 'Изображения мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Членство', 'verbose_name_plural': 'Членства'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Содержимое страницы', 'verbose_name_plural': 'Содержимое страниц'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Изображение проекта', 'verbose_name_plural': 'Изображения проектов'},
        ),
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': 'Участие в проекте', 'verbose_name_plural': 'Участия в проектах'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AlterModelOptions(
            name='сommunities',
            options={'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='description',
            field=models.TextField(verbose_name='Описание посла'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='image',
            field=models.ImageField(upload_to='ambasador/', verbose_name='Изображение посла'),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название посла'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='education',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(verbose_name='Описание образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to='education/', verbose_name='Изображение образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название образования'),
        ),
        migrations.AlterField(
            model_name='event',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='event_images/', verbose_name='Изображение мероприятия'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(verbose_name='Описание членства'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='image',
            field=models.ImageField(upload_to='membership/', verbose_name='Изображение членства'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название членства'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partner_logos/', verbose_name='Логотип партнёра'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название партнёра'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.projectparticipation', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='description',
            field=models.TextField(verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок проекта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service/', verbose_name='Изображение услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='сommunities',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='сommunities',
            name='description',
            field=models.TextField(verbose_name='Описание сообщества'),
        ),
        migrations.AlterField(
            model_name='сommunities',
            name='image',
            field=models.ImageField(upload_to='communities/', verbose_name='Изображение сообщества'),
        ),
        migrations.AlterField(
            model_name='сommunities',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название сообщества'),
        ),
    ]
