# Generated by Django 5.1.2 on 2024-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_ambassador_options_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ambassador', 'Посол'), ('education', 'Образование'), ('communities', 'Сообщество'), ('membership', 'Членство'), ('service', 'Услуга')], max_length=50, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='content_images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('additional_text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Контентный блок',
                'verbose_name_plural': 'Контентные блоки',
            },
        ),
        migrations.DeleteModel(
            name='Ambassador',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Сommunities',
        ),
    ]
