# Generated by Django 5.1.2 on 2024-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('community', 'Преимущества для сообщества'), ('events', 'Преимущества для мероприятий'), ('suppliers', 'Поставщики'), ('partners', 'Партнеры')], max_length=50, verbose_name='Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контентный блок',
                'verbose_name_plural': 'Контентные блоки',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Содержимое Членоствао',
                'verbose_name_plural': 'Содержимое Членоство',
            },
        ),
        migrations.CreateModel(
            name='StepInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
            ],
            options={
                'verbose_name': 'Пошаговая инструкция',
                'verbose_name_plural': 'Пошаговые инструкции',
            },
        ),
    ]
